# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12.x]
        browser: [chromium, firefox, webkit]
        exclude:
          - os: ubuntu-latest
            browser: webkit
          - os: windows-latest
            browser: webkit

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Test
        run: npm test
        env:
          BROWSER: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: snapshot-diffs
          path: src/__image_snapshots__/__diff_output__/
      - run: npm run report
